[package]
name = "config"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.10", features = ["luajit", "vendored"]}
nvim-oxi = {version = "0.6", features = ["neovim-0-11", "mlua"]}
